### ISSUE TITLE
que es esto

### ISSUE THREAD

**Issue by taprile314** [matias4205/QueueMasters#1]
contá wachin hacete un readme nose

**Comment by matiasperz** [comment]
Jasjsajsa lo estoy laburando todavia, pero es una app para poner en cola videos de youtube colaborativo, estoy armando tanto el backend como el frontend.

**Comment by matiasperz** [comment]
Va a quedar algo como esto 
![image](https://user-images.githubusercontent.com/43894343/71049878-83ad5180-2122-11ea-8942-4173fb38dfec.png)
